local_devices:
- name: pump
  displayed_name: Pumpe
  displayed_description: ''
  gpio: 13
  power: 800
  hysteresis_seconds: 60
  re_hysteresis_seconds: 60
  min_active_time_seconds: 1200
  shutdown_time_seconds: 7200
  temperature_safety:
  - value_degrees_c: 0
    end_value_degrees_c: -1
    type: low
    interval_seconds: 3600
    sensor_name: air
    alert_enabled: false
  - value_degrees_c: -1
    end_value_degrees_c: -3
    type: low
    interval_seconds: 1800
    sensor_name: air
    alert_enabled: false
  - value_degrees_c: -3
    type: low
    interval_seconds: 900
    duration_seconds: 90
    sensor_name: air
  max_active_time_seconds: 86400
  importance: 0
  power_off_tolerance: 0
- name: heat_pump
  displayed_name: Wärmepumpe
  displayed_description: ''
  gpio: 6
  power: 20000
  dependencies:
  - pump
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
- name: twizy
  displayed_name: Twizy Tankstelle
  displayed_description: ''
  power: 1500
  gpio: 1
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
- name: charging_point
  displayed_name: Ladestation
  displayed_description: ''
  power: 150
  gpio: 19
  hysteresis_seconds: 30
  importance: 0
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  re_hysteresis_seconds: 30
  shutdown_time_seconds: 0
  power_off_tolerance: 0
remote_devices:
- name: mobile_charging_station
  displayed_name: Mobile Ladestation
  displayed_description: ''
  host: iot-sonoff-2
  device_type: RemoteDeviceType.SONOFF
  power: 100
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 30
  re_hysteresis_seconds: 30
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
