local_devices:
- name: pump
  displayed_name: Pumpe
  displayed_description: ''
  gpio: 13
  power: 800
  hysteresis_seconds: 180
  re_hysteresis_seconds: 60
  min_active_time_seconds: 1200
  shutdown_time_seconds: 7200
  temperature_safety:
  - value_degrees_c: 0
    end_value_degrees_c: -1
    type: low
    interval_seconds: 3600
    sensor_name: air
    alert_enabled: false
  - value_degrees_c: -1
    end_value_degrees_c: -3
    type: low
    interval_seconds: 1800
    sensor_name: air
    alert_enabled: false
  - value_degrees_c: -3
    type: low
    interval_seconds: 900
    duration_seconds: 90
    sensor_name: air
  max_active_time_seconds: 86400
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: false
- name: heat_pump
  displayed_name: Wärmepumpe
  displayed_description: ''
  gpio: 6
  power: 2500
  dependencies:
  - pump
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 1500
  re_hysteresis_seconds: 180
  shutdown_time_seconds: 14400
  importance: 1
  power_off_tolerance: 200
  disable_automatic_management: false
- name: gate
  displayed_name: Tor
  displayed_description: ''
  power: 1
  gpio: 26
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 1
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: true
- name: chicken
  displayed_name: Hühner Wasser
  displayed_description: ''
  power: 1
  gpio: 5
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 900
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: true
- name: ambient_light
  displayed_name: Garten Beleuchtung
  displayed_description: ''
  power: 1
  gpio: 0
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 3600
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: true
- name: twizy
  displayed_name: Twizy Tankstelle
  displayed_description: ''
  power: 1500
  gpio: 1
  max_active_time_seconds: 7200
  min_active_time_seconds: 0
  hysteresis_seconds: 300
  re_hysteresis_seconds: 60
  shutdown_time_seconds: 3600
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: false
- name: charging_point
  displayed_name: Ladestation
  displayed_description: ''
  power: 150
  gpio: 19
  hysteresis_seconds: 180
  importance: 0
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 7200
  power_off_tolerance: 0
  disable_automatic_management: false
remote_devices:
- name: mobile_charging_station
  displayed_name: Mobile Ladestation
  displayed_description: ''
  host: 192.168.178.66
  device_type: RemoteDeviceType.SONOFF
  power: 100
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 180
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 3600
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: false
homeassistant_devices:
- name: lg_water_heater
  displayed_name: LG Wasser Heizung
  displayed_description: ''
  entity_id: water_heater.water_heater
  device_type: HomeAssistantDeviceType.LGWATERHEATER
  power: 650
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 3600
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: true
- name: lg_heat_pump
  displayed_name: LG Wärmepumpe
  displayed_description: 10°C relative Änderung
  entity_id: climate.heat_pump
  device_type: HomeAssistantDeviceType.LGHEATPUMP
  power: 3000
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 3600
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
  disable_automatic_management: true
dynamic_devices:
- name: lg_heat_pump_dynamic
  displayed_name: LG Wärmepumpe
  displayed_description: Heizkurve + PV-Überschuss
  power: 0
  controlled_device: lg_heat_pump
  buffer_sensor: bufferTop
  outdoor_sensor: air
  heat_pump_mode: 1
  outdoor_temp_cold_ref: -5
  outdoor_temp_warm_ref: 18
  design_supply_temp_max: 50
  design_supply_temp_min: 25
  pv_temp_boost_factor: 2
  param_update_delay: 180
  buffer_delta_supply: -2
  disable_automatic_management: false
  hardware_io_endpoint_mode: homeassistant
  ha_base_url: https://ha.florianschleuss.de
  ha_setpoint_webhook: SetHeatPumpReturnSetpoint
  ha_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiZGM3NTYwZDdhOGU0Nzc5YTY0ZjdkNDczNDU2M2E1NCIsImlhdCI6MTc2NDUyMDAyNSwiZXhwIjoyMDc5ODgwMDI1fQ.9lQ8F9MXl4p5G_Egdrf0ZxESGNTMRHC0IKlxKb0uKoM
  max_active_time_seconds: 86400
  min_active_time_seconds: 0
  hysteresis_seconds: 0
  re_hysteresis_seconds: 0
  shutdown_time_seconds: 0
  importance: 0
  power_off_tolerance: 0
  device_type: DynamicPowerSwitchable
  house_supply_setpoint: 25.456521739130434
  supply_gradient: 0.043478260869565216
  pv_boost_temp: 0.0
  heat_pump_return_setpoint: 25.456521739130434
  heat_pump_heat_wait: false
  last_param_update_ts: 1770376471.6177967
